<?php
return array(
    ['DISPLAY_DATE_FORMAT', 'm/d/Y'],
    ['DISPLAY_PHONE_FORMAT', 'XXX-XXX-XXXX'],
    ['EMAIL_DOMAIN', 'replaceme.com'],
    ['EMAIL_FORM_TO', 'me@replaceme.com'],
    ['ERROR_EMAIL_ADDRESS', 'webmaster@revealitconsulting.com'],
    ['PAGE_META_DESCRIPTION', 'My Company'],
    ['PAGE_META_KEYWORDS', 'My Company'],
    ['PAGE_TEMPLATE', 'base.twig'],
    ['PAGE_TITLE', 'My Company'],
    ['THEME_NAME', ''],
    ['ADMIN_THEME_NAME', ''],
    ['THEMES_DIR', ''],
    ['CSS_DIR_NAME', 'css'],
    ['HTML_DIR_NAME', 'html'],
    ['JS_DIR_NAME', 'js'],
    ['IMAGE_DIR_NAME', 'images'],
    ['ADMIN_DIR_NAME', 'manager'],
    ['ASSETS_DIR_NAME', 'assets'],
    ['FILES_DIR_NAME', 'files'],
    ['PRIVATE_DIR_NAME', 'private'],
    ['TMP_DIR_NAME', 'tmp'],
    ['DEVELOPER_MODE', false],
    ['ENCRYPT_TYPE', 'cleartext'],
    ['FTP_BASE_PATH', '/srv/websites'],
    ['SYSTEM_USER_ID', 1001],
    ['SYSTEM_GROUP_ID', 81],
);
