<?php
return array(
    'Wer\Framework\Helper\ViewHelper'        => APP_PATH . '/Framework/Helper/ViewHelper.php',
    'Wer\Framework\Library\Access'           => APP_PATH . '/Framework/Library/Access.php',
    'Wer\Framework\Library\Actions'          => APP_PATH . '/Framework/Library/Actions.php',
    'Wer\Framework\Library\Arrays'           => APP_PATH . '/Framework/Library/Arrays.php',
    'Wer\Framework\Library\Autoloader'       => APP_PATH . '/Framework/Library/Autoloader.php',
    'Wer\Framework\Library\Base'             => APP_PATH . '/Framework/Library/Base.php',
    'Wer\Framework\Library\Config'           => APP_PATH . '/Framework/Library/Config.php',
    'Wer\Framework\Library\Database'         => APP_PATH . '/Framework/Library/Database.php',
    'Wer\Framework\Library\Date_Time'        => APP_PATH . '/Framework/Library/Date_Time.php',
    'Wer\Framework\Library\Elog'             => APP_PATH . '/Framework/Library/Elog.php',
    'Wer\Framework\Library\Files'            => APP_PATH . '/Framework/Library/Files.php',
    'Wer\Framework\Library\HTML'             => APP_PATH . '/Framework/Library/Html.php',
    'Wer\Framework\Library\Location'         => APP_PATH . '/Framework/Library/Location.php',
    'Wer\Framework\Library\Session'          => APP_PATH . '/Framework/Library/Session.php',
    'Wer\Framework\Library\Strings'          => APP_PATH . '/Framework/Library/Strings.php',
    'Wer\Framework\Library\Tail'             => APP_PATH . '/Framework/Library/Tail.php',
    'Wer\Framework\Library\Tester'           => APP_PATH . '/Framework/Library/Tester.php',
    'Wer\Guide\Controller\BaseController'    => APP_PATH . '/Guide/Controller/BaseController.php',
    'Wer\Guide\Controller\ItemController'    => APP_PATH . '/Guide/Controller/ItemController.php',
    'Wer\Guide\Controller\MainController'    => APP_PATH . '/Guide/Controller/MainController.php',
    'Wer\Guide\Controller\ManagerController' => APP_PATH . '/Guide/Controller/ManagerController.php',
    'Wer\Guide\Controller\SearchController'  => APP_PATH . '/Guide/Controller/SearchController.php',
    'Wer\Guide\Controller\TestsController'   => APP_PATH . '/Guide/Controller/TestsController.php',
    'Wer\Guide\Forms\Entity\QuickSearch'     => APP_PATH . '/Guide/Forms/Entity/QuickSearch.php',
    'Wer\Guide\Forms\SearchForms'            => APP_PATH . '/Guide/Forms/SearchForms.php',
    'Wer\Guide\Model\Category'               => APP_PATH . '/Guide/Model/Category.php',
    'Wer\Guide\Model\Field'                  => APP_PATH . '/Guide/Model/Field.php',
    'Wer\Guide\Model\Item'                   => APP_PATH . '/Guide/Model/Item.php',
    'Wer\Guide\Model\Section'                => APP_PATH . '/Guide/Model/Section.php',
    'Wer\Import\Controller\MainController'   => APP_PATH . '/Import/Controller/MainController.php',
);
