<?php
return [
    'read'
];
/*
return [
    'read',
    'create',
    'update',
    'delete',
    'getPeopleId',
    'incrementBadLoginCount',
    'incrementBadLoginTimestamp',
    'readPeopleRecord',
    'resetBadLoginCount',
    'resetBadLoginTimestamp',
    'setBadLoginTimestamp',
    'setLoggedIn',
    'setLoggedOut',
    'updatePassword',
    'updateActive',
    'readInfo',
    'savePerson',
    'deletePerson',
    'isId',
    'makeGroupIdArray',
    'makePgmArray',
    'getErrorMessage'
];
*/
