<?php
return [
    'read',
    'create',
    'update',
    'delete',
    'getUserId',
    'incrementBadLoginCount',
    'incrementBadLoginTimestamp',
    'readUserRecord',
    'resetBadLoginCount',
    'resetBadLoginTimestamp',
    'setBadLoginTimestamp',
    'updatePassword',
    'updateActive',
    'readInfo',
    'readUsersInfo',
    'saveUser'
];
